







	



.build/uno/Ethernet/utility/socket.d : /usr/share/arduino/libraries/Ethernet/utility/socket.cpp
	@mkdir -p .build/uno/Ethernet/utility
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility  -MM $^ > $@
	
	@printf ".build/uno/Ethernet/utility/socket.d .build/uno/Ethernet/utility/" | cat - $@ > $@~ && mv $@~ $@

.build/uno/Ethernet/utility/w5100.d : /usr/share/arduino/libraries/Ethernet/utility/w5100.cpp
	@mkdir -p .build/uno/Ethernet/utility
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility  -MM $^ > $@
	
	@printf ".build/uno/Ethernet/utility/w5100.d .build/uno/Ethernet/utility/" | cat - $@ > $@~ && mv $@~ $@

.build/uno/Ethernet/EthernetClient.d : /usr/share/arduino/libraries/Ethernet/EthernetClient.cpp
	@mkdir -p .build/uno/Ethernet
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility  -MM $^ > $@
	
	@printf ".build/uno/Ethernet/EthernetClient.d .build/uno/Ethernet/" | cat - $@ > $@~ && mv $@~ $@

.build/uno/Ethernet/EthernetServer.d : /usr/share/arduino/libraries/Ethernet/EthernetServer.cpp
	@mkdir -p .build/uno/Ethernet
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility  -MM $^ > $@
	
	@printf ".build/uno/Ethernet/EthernetServer.d .build/uno/Ethernet/" | cat - $@ > $@~ && mv $@~ $@

.build/uno/Ethernet/Ethernet.d : /usr/share/arduino/libraries/Ethernet/Ethernet.cpp
	@mkdir -p .build/uno/Ethernet
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility  -MM $^ > $@
	
	@printf ".build/uno/Ethernet/Ethernet.d .build/uno/Ethernet/" | cat - $@ > $@~ && mv $@~ $@

.build/uno/Ethernet/Dhcp.d : /usr/share/arduino/libraries/Ethernet/Dhcp.cpp
	@mkdir -p .build/uno/Ethernet
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility  -MM $^ > $@
	
	@printf ".build/uno/Ethernet/Dhcp.d .build/uno/Ethernet/" | cat - $@ > $@~ && mv $@~ $@

.build/uno/Ethernet/EthernetUdp.d : /usr/share/arduino/libraries/Ethernet/EthernetUdp.cpp
	@mkdir -p .build/uno/Ethernet
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility  -MM $^ > $@
	
	@printf ".build/uno/Ethernet/EthernetUdp.d .build/uno/Ethernet/" | cat - $@ > $@~ && mv $@~ $@

.build/uno/Ethernet/Dns.d : /usr/share/arduino/libraries/Ethernet/Dns.cpp
	@mkdir -p .build/uno/Ethernet
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility  -MM $^ > $@
	
	@printf ".build/uno/Ethernet/Dns.d .build/uno/Ethernet/" | cat - $@ > $@~ && mv $@~ $@



.build/uno/Ethernet/dependencies.d : .build/uno/Ethernet/utility/socket.d .build/uno/Ethernet/utility/w5100.d .build/uno/Ethernet/EthernetClient.d .build/uno/Ethernet/EthernetServer.d .build/uno/Ethernet/Ethernet.d .build/uno/Ethernet/Dhcp.d .build/uno/Ethernet/EthernetUdp.d .build/uno/Ethernet/Dns.d
	@echo [96mScanning dependencies of Ethernet[0m
	@mkdir -p .build/uno/Ethernet
	@cat $^ > $@;

all : .build/uno/Ethernet/dependencies.d
	@true

